apiVersion: v1
kind: ServiceAccount
metadata:
  name: externaldnspublic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externaldnspublic
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: externaldnspublic-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: externaldnspublic
subjects:
- kind: ServiceAccount
  name: externaldnspublic
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: externaldnspublic
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: externaldnspublic
  template:
    metadata:
      labels:
        app: externaldnspublic
    spec:
      serviceAccountName: externaldnspublic
      containers:
      - name: externaldnspublic
        image: k8s.gcr.io/external-dns/external-dns:v0.7.9 
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=dev.hi.solidstateops.com # (optional) limit to only example.com domains; change to match the zone created above.
        - --provider=azure
        - --azure-subscription-id=8fb55161-82ce-4110-9cbb-3400b5271a8c #this is called out by https://github.com/kubernetes-sigs/external-dns/issues/1782 as required for private dns externalDNS deployment, but i'm adding it to this private DNS args just in case
        volumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-config-file
        secret:
          secretName: azure-config-file
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: externaldnsprivate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externaldnsprivate
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: externaldnsprivate-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: externaldnsprivate
subjects:
- kind: ServiceAccount
  name: externaldnsprivate
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: externaldnsprivate
spec:
  selector:
    matchLabels:
      app: externaldnsprivate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: externaldnsprivate
    spec:
      serviceAccountName: externaldnsprivate
      containers:
      - name: externaldnsprivate
        image: k8s.gcr.io/external-dns/external-dns:v0.7.9
        env:
        - name: AZURE_CLIENT_ID
          value: ab98e10d-e1fa-449c-b17f-fcf0b3fe453d
        - name: AZURE_CLIENT_SECRET
          value: OuRAxcT10yeWjW8NyK-uKlW.Q6P2DjRUWr
        - name: AZURE_SUBSCRIPTION_ID
          value: 8fb55161-82ce-4110-9cbb-3400b5271a8c
        - name: AZURE_TENANT_ID
          value: 88d74dfa-951f-4916-8b9e-bebe3a025601
        args:
        - --source=service
        - --source=ingress
        - --provider=azure-private-dns
        - --domain-filter=dev.hi.internal.solidstateops.com # (optional) limit to only example.com domains; change to match the zone created above.
        - --azure-subscription-id=8fb55161-82ce-4110-9cbb-3400b5271a8c #this is called out by https://github.com/kubernetes-sigs/external-dns/issues/1782 as required for private dns externalDNS deployment, but i'm not sure of that yet
        volumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-config-file
        secret:
          secretName: azure-config-file