apiVersion: v1
kind: ServiceAccount
metadata:
  name: externaldnspublic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externaldnspublic
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: externaldnspublic-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: externaldnspublic
subjects:
- kind: ServiceAccount
  name: externaldnspublic
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: externaldnspublic
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: externaldnspublic
  template:
    metadata:
      labels:
        app: externaldnspublic
    spec:
      serviceAccountName: externaldnspublic
      containers:
      - name: externaldnspublic
        image: k8s.gcr.io/external-dns/external-dns:v0.7.3
        args:
        - --source=service
        - --source=ingress
        # - --domain-filter=example.com # (optional) limit to only example.com domains; change to match the zone created above.
        - --provider=azure
        - --azure-resource-group=dev-hi-sso-arg-tf # (optional) use the DNS zones from the tutorial's resource group
        volumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-config-file
        secret:
          secretName: azure-config-file