apiVersion: v1
kind: ServiceAccount
metadata:
  name: externaldnsprivate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externaldnsprivate
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: externaldnsprivate-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: externaldnsprivate
subjects:
- kind: ServiceAccount
  name: externaldnsprivate
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: externaldnsprivate
spec:
  selector:
    matchLabels:
      app: externaldnsprivate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: externaldnsprivate
    spec:
      serviceAccountName: externaldnsprivate
      containers:
      - name: externaldnsprivate
        image: k8s.gcr.io/external-dns/external-dns:v0.7.3
        args:
        - --source=service
        - --source=ingress
        #- --domain-filter=example.com
        - --provider=azure-private-dns
        - --azure-resource-group=dev-hi-sso-arg-tf
        - --azure-subscription-id=8fb55161-82ce-4110-9cbb-3400b5271a8c
        volumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-config-file
        secret:
          secretName: azure-config-file